/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 D:\projects\arStore\AR-Store\frontend-AR\public\models\wooden_table.glb --keepnames --shadows 
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-acd1cef307b94803846d624b251a4e63
Title: Wooden Table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Wooden_table(props) {
  const { nodes, materials } = useGLTF("/models/wooden_table.glb");
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.036}
      >
        <mesh
          name="defaultMaterial"
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Default}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/wooden_table.glb");
